services:
  rockfeed:
    build:
      context: .
      args:
        VERSION: ${VERSION:-0.1.0}
    image: rockfeed-rj:${VERSION:-0.1.0}
    container_name: rockfeed-rj
    ports:
      - "8765:8765"
    volumes:
      - ./app/data:/app/data:Z
    restart: unless-stopped
