services:
  rockfeed:
    build: .
    image: rockfeed-rj:latest
    container_name: rockfeed-rj
    ports:
      - "8765:8765"
    volumes:
      - ./app/data:/app/data:Z
    restart: unless-stopped
